### PR TITLE
fixing jWizard examples, not complete though

### PR DESCRIPTION
**Pull request by brgrz**
some don't work even after fixing the paths

### CODE REVIEW

**Comment by dominicbarnes** [comment]
Ah, I'd forgotten about these examples. I don't link to them anymore on the documentation site, I'm considering just dropping that entire directory.

Is there much value in having examples in the repository itself? Since you're submitting a PR, I imagine you've found them useful?

**Comment by brgrz** [comment]
well, the docs at http://www.dbarnes.info/jWizard/ are nice but examples often provide a better understanding and are easy to try out, it was the first thing I check out when I downloaded jWizard for the first time. Since they weren't working, I pulled out the Dev tools and found out some URLs were wrong, so I fixed them.

Some of the examples still don't work, I guess the code changed and they became invalid.

I tried out a few of other wizard scripts and most are pretty unclear, not documented etc., I think you could produce something nice here if you stick to it and I hope we (the community) will be able to help you as much as possible.

Currently we have dozens of lightbox clone libriaries, of which a few of them are great and one can really rely on them but we have nothing such when it comes to JS wizards.

**Comment by dominicbarnes** [comment]
That seems reasonable, yeah the truth is those examples are all completely out of date now. I'll spend some time this weekend creating a good batch of examples for all the most common use-cases. If you have any requests, I'd love to hear them!

**Comment by brgrz** [comment]
I figured out the children() method was picking up everything when I had an input field inside the form but outside the steps (it was an input field for anti forgery token by ASP.NET MVC).
Added an option to set allowed tags for steps and fixed the buildSteps() function to use it.

Please let me know if this is the way you want forked commits. Or should we edit the src directory?

**Comment by daogurtsov** [comment]
I found out that events example isn't working, and  it's not sources urls issue. I can't find why. It will be great if you'll fix it.

**Comment by dominicbarnes** [comment]
I won't merge this PR, instead check out my new branch, [feature/examples](https://github.com/dominicbarnes/jWizard/tree/feature/examples).

Any feedback on additional examples would be nice. I'll probably merge it in pretty soon, and just accept PRs for additions/modifications.

**Pull request closed without merging**
